Numpy Arrays 

In [4]:
height = [1.87,  1.87, 1.82, 1.91, 1.90, 1.85]
weight = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]

import numpy as np 

np_height = np.array(height)
np_weight = np.array(weight)

print(type(np_height))

<class 'numpy.ndarray'>


In [6]:
bmi = np_weight / np_height **2
print(bmi)

[23.34925219 27.88755755 28.75558507 25.48723993 23.87257618 25.84368152]


In [7]:
bmi > 23

array([ True,  True,  True,  True,  True,  True])

In [8]:
bmi[bmi>23]

array([23.34925219, 27.88755755, 28.75558507, 25.48723993, 23.87257618,
       25.84368152])